# Generated by Django 3.0.8 on 2020-07-21 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alllisting_bid_closedbid_comment_listing_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='decription',
            new_name='description',
        ),
    ]
